### ISSUE TITLE
Patch versions of `2024.03` are missing at PyPI

### ISSUE THREAD

**Issue by padix-key** [kuelumbus/rdkit-pypi#103]
Currently, the latest version on PyPI is `2024.03.01`. However the RDKit version `2024.03.02` and `2024.03.03` [already exist](https://github.com/rdkit/rdkit/releases) on GitHub.

**Comment by janosch-achenbach** [comment]
Thanks a lot @kuelumbus for your support to provide the PyPi releases of rdkit. Very much appreciated! Are there any updates on the PR of the latest version? By now we have another new minor release 2024.03.04 and it seems to be pending / stucked as well. Any idea when you will be able to review the PR and trigger the new relesase?

Thank you very much!

**Comment by c-w-feldmann** [comment]
@janosch-achenbach, I think the is fighting with the versioning, See [PR100](https://github.com/kuelumbus/rdkit-pypi/pull/100).

**Comment by kuelumbus** [comment]
I know the updates are currently taking long. I'm having difficulties with the Windows RDKit builds, but I'm working on it and will get the update out as soon as I can.
