### ISSUE TITLE
bad_alloc was found while trying to load Chem moduel in with Python import

### ISSUE THREAD

**Issue by Kh4L** [kuelumbus/rdkit-pypi#112]
x-posting from https://github.com/rdkit/rdkit/issues/7735 

This is observed with [2024.3.3 package]( https://github.com/kuelumbus/rdkit-pypi/commit/c63fb37ad53acd8eb753f6635931f08489e3ddf2 ) but doesn't appear in 2024.3.2 and older packages.

Full details available in https://github.com/rdkit/rdkit/issues/7735

**Comment by kuelumbus** [comment]
I can't repo this on my ubuntu machine with python 3.12: 

```
➜  chris ~ ipython
Python 3.12.3 (main, Jul 31 2024, 17:43:48) [GCC 13.2.0]
Type 'copyright', 'credits' or 'license' for more information
IPython 8.17.2 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import accelerate
   ...: from rdkit import Chem

In [2]: 
```

Might be related to your specific machine or setup.

**Comment by kuelumbus** [comment]
> @kuelumbus What's the ubuntu version?

24.03

(`/usr/lib/aarch64-linux-gnu/libstdc++.so.6.0.30`)
From https://github.com/rdkit/rdkit/issues/7735,  it seems like you are on aarch64 linux?

**Comment by Kh4L** [comment]
Closing this https://github.com/rdkit/rdkit/issues/7735#issuecomment-2307395225
