### ISSUE TITLE
ERROR: 132

### ISSUE THREAD

**Issue by curcioriccardo** [kuelumbus/rdkit-pypi#35]
Configuration :

RDKit version: 2021.9.5.1
OS: Ubuntu 18.04.3 LTS
Python version (if relevant): 3.9
Are you using conda? No
If you are not using conda: how did you install the RDKit? Both via pip install rdkit-pypi and from source code.

Hello, i am having trouble running rdkit in python. 
In particular i get ERROR: 132 by running this minimal code from the pip install tutorial, without any explanation : from rdkit import Chem;print(Chem.MolToMolBlock(Chem.MolFromSmiles('C1CCC1')))
I installed rdkit also from git and i get the same error.

Thanks for the support.
Best regards.

Additional context
Creating parametersdistributions-ml_app_run ... done
Python 3.9.2 (default, Feb 28 2021, 17:03:44)
[GCC 10.2.1 20210110] on linux
Type "help", "copyright", "credits" or "license" for more information.

from rdkit import Chem; print(Chem.MolToMolBlock(Chem.MolFromSmiles('C1CCC1')))
ERROR: 132

**Comment by kuelumbus** [comment]
I can't reproduce this, and I don't think this is related to RDKit or the pypi package.

**Comment by curcioriccardo** [comment]
> I can't reproduce this, and I don't think this is related to RDKit or the pypi package.

Actually using a specific version (rdkit-pypi==2021.3.1.1) the code works. Do you know what could be the cause? Thanks.

**Comment by kuelumbus** [comment]
Ok. Docker is good. Can you provide the container to me or the Dockerfile to produce this? Also, are you running on aarch64 Linux? (Just wondering because 2021.9.5 had issues on aarch64).

**Comment by curcioriccardo** [comment]
Unfortunately no.
By looking at this other discussion: https://github.com/rdkit/rdkit/issues/3814 i think it is a CPU problem.

**Comment by kuelumbus** [comment]
What CPU do you use?

Check out the [no popcnt branch](/kuelumbus/rdkit-pypi/tree/no_POPCNT). This should produce wheels without the popcnt instructions at https://github.com/kuelumbus/rdkit-pypi/actions/runs/2110102013. Can you try the wheels when they are done?

**Comment by curcioriccardo** [comment]
These are the CPU specs:
Architecture:        x86_64
CPU op-mode(s):      32-bit, 64-bit
Byte Order:          Little Endian
CPU(s):              8
On-line CPU(s) list: 0-7
Thread(s) per core:  2
Core(s) per socket:  2
Socket(s):           2
NUMA node(s):        1
Vendor ID:           GenuineIntel
CPU family:          15
Model:               6
Model name:          Intel(R) Xeon(TM) CPU 3.00GHz
Stepping:            4
CPU MHz:             1992.000
CPU max MHz:         2988,0000
CPU min MHz:         1992,0000
BogoMIPS:            5984.98
Virtualization:      VT-x
L1d cache:           16K
L2 cache:            2048K
NUMA node0 CPU(s):   0-7
Flags:               fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx lm constant_tsc pebs bts nopl cpuid pni dtes64 monitor ds_cpl vmx est cid cx16 xtpr pdcm lahf_lm pti tpr_shadow

Yes, i will try them.

**Comment by curcioriccardo** [comment]
Hi, i tried the new wheels and still same error ( Illegal instruction (core dumped)).
The only version working is still "2021.3.1.1".
