### ISSUE TITLE
RDKit-PyPi Numpy >= 1.19 Dependency

### ISSUE THREAD

**Issue by amirnikooie** [kuelumbus/rdkit-pypi#38]
Hello,

I noticed rdkit-pypi requires numpy >= 1.19. This is the case even with older versions of the package. However, since I have a project that uses tensorflow 2.3 and that version of tensorflow is compatible with numpy < 1.19, I ignored the dependency and it worked fine. So, my question is how to lower the dependency to numpy to version 1.18 or is there at least an older version of rdkit-pypi that supports numpy < 1.19? In general, is numpy version 1.19 really required?
The reason behind this request is that I'm building a container that installs every package in 'requirements.txt' automatically and such dependency errors stops the whole process.  So, it's not just a one time installation for which the error can be ignored.
Thanks in advance for your help!

**Comment by kuelumbus** [comment]
The reason was that, starting at 1.19, Numpy platform wheels are available for Python 3.9. But I can make the Numpy version dependent on the Python versions. This should solve your issue.

**Comment by BvB93** [comment]
Perhaps this could be of use: https://pypi.org/project/oldest-supported-numpy/

**Comment by kuelumbus** [comment]
Please see the new version on PyPi. `2022.3.1.1` can now be installed with any numpy version. The minimum numpy version is the one defined in https://github.com/scipy/oldest-supported-numpy/blob/main/setup.cfg.

**Comment by amirnikooie** [comment]
Thanks @kuelumbus for your prompt action on this!
