### ISSUE TITLE
cibuildwheel fails on dev laptop due to use of CIBW_BUILD in setup.py

### ISSUE THREAD

**Issue by sconstable** [kuelumbus/rdkit-pypi#42]
Hello @kuelumbus ! Thanks for your work on this project.

I'm evaluating rdkit-pypi for use at my company and I think I've noticed an issue.  I tried running the `cibuildwheel --platform linux --output-dir wheelhouse` as described in the docs, which should build the linux wheels on my local machine using Docker.  Unfortunately, the build failed with an error in setup.py.  It seems that in checking for the macOS arm64 platform, we run the following line
```
if "macosx_arm64" in os.environ["CIBW_BUILD"]:
```
which breaks in local mode since CIBW_BUILD never gets defined.  I am now testing the build with the following patches:
```
@@ -91,8 +91,8 @@ class BuildRDKit(build_ext_orig):
             cmd += [f"--build=b2"]
 
         # for arm 64 on MacOS
-        if "macosx_arm64" in os.environ["CIBW_BUILD"]:
-            cmd += ["-s", "arch=armv8", "-s", "arch_build=armv8"]
+        #if "macosx_arm64" in os.environ["CIBW_BUILD"]:
+        #    cmd += ["-s", "arch=armv8", "-s", "arch_build=armv8"]
 
         check_call(cmd)

@@ -187,13 +187,13 @@ class BuildRDKit(build_ext_orig):
             ]
 
         vars = {}
-        if "macosx_arm64" in os.environ["CIBW_BUILD"]:
-            options += [
-                "-DCMAKE_OSX_ARCHITECTURES=arm64",
-                "-DRDK_OPTIMIZE_POPCNT=OFF",
-            ]
-            # also export it to compile yaehmop for arm64 too
-            vars["CMAKE_OSX_ARCHITECTURES"] = "arm64"
+        #if "macosx_arm64" in os.environ["CIBW_BUILD"]:
+        #    options += [
+        #        "-DCMAKE_OSX_ARCHITECTURES=arm64",
+        #        "-DRDK_OPTIMIZE_POPCNT=OFF",
+        #    ]
+        #    # also export it to compile yaehmop for arm64 too
+        #    vars["CMAKE_OSX_ARCHITECTURES"] = "arm64"
 
         cmds = [
             f"cmake -S . -B build {' '.join(options)}",
```
Obviously this will break the arm64 mac builds, but it should restore local build functionality.  Maybe there's an alternative way to detect the macOS arm64 platform?

**Comment by kuelumbus** [comment]
Thanks for this. I haven't tried to build this locally in a while.

Does this also happen if you run  with the `--config-file` option? The option `environment-pass` in `pyproject.toml` should pass the environment variable `CIBW_BUILD` to the docker container.

Something like:
`cibuildwheel --platform linux --output-dir wheelhouse --config-file pyproject.toml`

https://github.com/kuelumbus/rdkit-pypi/blob/728555219dd9dce316e274f6cc9fdb8a59ba4e79/pyproject.toml#L40-L43

**Comment by sconstable** [comment]
I will try this once my current build finishes but I don't expect it will work - it would pass in CIBW_BUILD if it was defined but unless it known to repeatedly set it and pass it in then the automatic build across multiple python versions won't work.

**Comment by kuelumbus** [comment]
Yes, you're right.  `CIBW_BUILD` is set in the Github action file. 🤭 

Try:
```sh
CIBW_BUILD=cp37-manylinux_x86_64 cibuildwheel --platform linux --output-dir wheelhouse --config-file pyproject.toml
```
Replace  `cp37` with `cp38`,  `cp39`, `cp310` for other python versions. Let me know if this works. I will update the documentation.

**Comment by sconstable** [comment]
Hey! So I finished running my build overnight, but when I checked it this morning it had failed because it attempted to build pypy packages, which I believe since rdkit is written in C that this will always fail.  Unfortunately, that means that none of the other cpython wheels were saved :'(

I tried your method this morning (explicitly setting `CIBW_BUILD`) and it works! Thanks for your help. I do think the docs should be updated to reflect this.

**Comment by kuelumbus** [comment]
FYI. It probably fails because you are building RDKit for all python versions in one docker container without setting `CIBW_BUILD`. But the code is not built for this. You can only build one RDKit version for a specific Python version per container.
