### ISSUE TITLE
cannot import name 'rdFreeSASA' from 'rdkit.Chem'

### ISSUE THREAD

**Issue by sfias** [kuelumbus/rdkit-pypi#43]
Hi, I've installed the latest version of RDKit using rdkit-pypi, but it seems this does not install rdFreeSASA. 
`from rdkit.Chem import rdFreeSASA`
I get the error:
ImportError: cannot import name 'rdFreeSASA' from 'rdkit.Chem' (/[...]/rdkit/Chem/__init__.py)
Is there a way to install rdFreeSASA using `pip install rdkit-pypi`?
Thank you
Stijn

**Comment by kuelumbus** [comment]
Thanks for pointing this out. I have enabled FreeSASA. The next version should have it included.
