### ISSUE TITLE
ImportError: No module named rdkit

### ISSUE THREAD

**Issue by sophialeeman** [kuelumbus/rdkit-pypi#46]
After I seemed to have successfully installed rdkit by running 

`python -m pip install rdkit-pypi --user`

and 

`python -c "from rdkit import Chem; print(Chem.MolToMolBlock(Chem.MolFromSmiles('C1CCC1')))"`

with no issues,

I am getting the following error:
"ImportError: No module named rdkit"

when I try to run a pytest on a tool I am trying to use called e3fp.

Could you provide any advice?

Thank you for your help!

**Comment by kuelumbus** [comment]
I don't think this has anything to do with the package. My guess is that you are using a different environment or python interpreter (or different python version) when you import RDKit. Please provide more details.

**Comment by kuelumbus** [comment]
There hasn't been a reply in some time. I'm closing this issue. Please feel free to reopen.

**Comment by sophialeeman** [comment]
I apologize! I forgot about this request after looking into the environment I was using. You are right. It had nothing to do with RDkit. Thank you for your help!
