### ISSUE TITLE
Turn on RDK_BUILD_XYZ2MOL_SUPPORT

### ISSUE THREAD

**Issue by jhjensen2** [kuelumbus/rdkit-pypi#62]
Is it possible to turn on [RDK_BUILD_XYZ2MOL_SUPPORT](https://github.com/rdkit/rdkit/blob/739b417dfe3826ad6ad02b5d812459804684bc30/CMakeLists.txt#L56) in the pip distribution?

**Comment by kuelumbus** [comment]
Absolutely. Seems like this is a newer option that I have missed to activate.

**Comment by jhjensen2** [comment]
How long does it take to go into effect? It's still not working for me: [https://colab.research.google.com/drive/1PPN4Acvk93E0nhRbj4MSNDQd0b6Lo_c5?usp=sharing](https://colab.research.google.com/drive/1PPN4Acvk93E0nhRbj4MSNDQd0b6Lo_c5?usp=sharing)
