### ISSUE TITLE
Python 3.11 support on PyPI comes with RDKit release 2022.9.2

### ISSUE THREAD

**Issue by gedeck** [kuelumbus/rdkit-pypi#66]
The pypi package on https://pypi.org/project/rdkit/ only supports Python versions up to 3.10 while this repository indicates support for 3.11. 

When do you plan to update the package?

**Comment by kuelumbus** [comment]
I am waiting for the new RDKit version (which should be released this week) to upload the 3.11 builds.  I should have waited for the new version before merging the 3.11 PR. Sorry for the confusion.

Please leave this issue open. I will close it when the builds are up. 

Related #64

**Comment by gedeck** [comment]
No problem. I thought Greg already release it. Thank you for your work with the packaging; I greatly appreciate it!

**Comment by KrisVolkova** [comment]
Hello! Could you please do it? I will be happy :) Thank you a lot! 
We have Python 3.11 and need RDKit for it
