### ISSUE TITLE
Version mismatch due to setuptools cutting trailing zeros?

### ISSUE THREAD

**Issue by j3mdamas** [kuelumbus/rdkit-pypi#74]
Hi,

This is very minor, but I noticed it yesterday when it was relevant for a project I was working on.

I noticed that the metadata version from pip does not have the trailing zero on the minor. E.g., pip will report [2022.9.5](https://pypi.org/project/rdkit/2022.9.5/), while `rdkit.__version__` reports 2022.09.5.

From what I see on your `setup.py`, the [version metadata](https://github.com/kuelumbus/rdkit-pypi/blob/5f8511a6a81d63ab1df1efbe2eaf510c08446a16/setup.py#L305) does not seem to have any bug, so my current idea is that setuptools is cutting the trailing zero. Any other idea?

**Comment by kuelumbus** [comment]
Hi,
[PEP 440](https://peps.python.org/pep-0440/) defines the version identification for python packages.  You are right that setuptools automatically normalizes the version identification.

Check for example:
https://github.com/kuelumbus/rdkit-pypi/actions/runs/4275512426/jobs/7442915729#step:7:268

`UserWarning: Normalizing '2022.09.5' to '2022.9.5'`

Nothing I can do here. RDKit's versioning scheme would need to be changed. 

Chris

**Comment by j3mdamas** [comment]
Makes sense, thanks for the quick answer @kuelumbus :)
