### ISSUE TITLE
Missing/invalid X11 libraries dependencies for libcairo on GNU/Linux

### ISSUE THREAD

**Issue by grgi** [kuelumbus/rdkit-pypi#75]
The packaged 3rd party library `libcairo` has dependencies which are not included (or refer to an unmodified name).
In particular `libXau` and `libXdmcp` are not found unless they are installed by the OS. In most installations, this is not a problem, but a vanilla container image might not include any X11 libraries.

**Comment by kuelumbus** [comment]
Can you install the missing libraries on your Linux distribution using the package manager (apt, ...)? 

And can you point out the vanilla container image which is missing the libs?

**Comment by grgi** [comment]
Of course, installing would help, but I thought Python Wheels should include all dependencies other than `libc`.

Pick any basic docker image, e.g. `debian:latest`. Here is an example output:
```
/tmp/rdkit/lib/python3.9/site-packages/rdkit.libs# ldd libcairo-ddd0c49f.so.2.11514.0 
	linux-vdso.so.1 (0x00007ffed23d5000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f515ab61000)
	libpixman-1-f094a0b6.so.0.34.0 => not found
	libfreetype-c0e61f0c.so.6.14.0 => not found
	libpng15-ce838cd1.so.15.13.0 => not found
	libxcb-shm-7a199f70.so.0.0.0 => not found
	libxcb-65da195c.so.1.1.0 => not found
	libxcb-render-637b984a.so.0.0.0 => not found
	libXrender.so.1 => not found
	libX11.so.6 => not found
	libXext.so.6 => not found
	libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007f515ab42000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f515ab36000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f515a9f2000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f515a81d000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f515acac000)
```
Here `libXrender`, `libX11` and `libXext` are not found but also not supplied.

**Comment by kuelumbus** [comment]
You're right that all dependencies should be included. But the libs you mentioned are explicitly excluded (for some reason) from the platform wheels.

[Auditwheel](https://github.com/pypa/auditwheel) is taking care of creating the platform wheel. See these [policy lines]( https://github.com/pypa/auditwheel/blob/63c30761e6857491af50fbb1922ecfd4c034ef76/src/auditwheel/policy/manylinux-policy.json#L128) that explicitly exclude these libs. 


```json
 "lib_whitelist": [
         "libgcc_s.so.1",
         "libstdc++.so.6",
         "libm.so.6", "libdl.so.2", "librt.so.1",
         "libc.so.6", "libnsl.so.1", "libutil.so.1", "libpthread.so.0",
         "libX11.so.6", "libXext.so.6", "libXrender.so.1", "libICE.so.6",
         "libSM.so.6", "libGL.so.1", "libgobject-2.0.so.0",
         "libgthread-2.0.so.0", "libglib-2.0.so.0", "libresolv.so.2",
         "libexpat.so.1",
         "libz.so.1"
     ],
```

Looks like an explanation can be found in https://github.com/pypa/auditwheel/issues/78. 

Does this answer your question?

**Comment by grgi** [comment]
Yes, I did not know that. And thank you for the explanation!

**Comment by liquidcarbon** [comment]
I've been trying to put rdkit on AWS Lambda and eventually succeeded by finding all `/lib64` files referenced in `rdkit.libs` and packaging them together into rdkit lambda layer.  I'm curious why don't you bring them all into `rdkit.libs`? they're not very large, ~4 MB all together.

/lib64/ld-linux-x86-64.so.2 
/lib64/libX11.so.6 
/lib64/libXau.so.6 
/lib64/libXext.so.6 
/lib64/libXrender.so.1 
/lib64/libc.so.6 
/lib64/libdl.so.2 
/lib64/libexpat.so.1 
/lib64/libgcc_s.so.1 
/lib64/libm.so.6 
/lib64/libpthread.so.0 
/lib64/librt.so.1 
/lib64/libstdc++.so.6 
/lib64/libutil.so.1 
/lib64/libxcb.so.1 
/lib64/libz.so.1

```
for f in $(for f in `find rdkit.libs/ -type f`; do ldd $f | grep -v "not found" | grep "0x0" | grep -oE "(/lib64.*) "; done | sort -u); do cp -L $f rdkit.libs/; done
```

**Comment by kuelumbus** [comment]
To my understanding, these libs should not be included in the wheel according to PEP513 that's why Auditwheel exudes them. 

4MB would be a 18% increase.
