### ISSUE TITLE
`rdkit.rdBase.boostVersion` is empty string in latest release installed from PyPI using pip

### ISSUE THREAD

**Issue by radusuciu** [kuelumbus/rdkit-pypi#88]
I consult `rdkit.rdBase.boostVersion` to determine what version of `boost` any given version of `rdkit` has been built with like so: `python -c "import rdkit; print(rdkit.rdBase.boostVersion)"`. With the latest release, I get back an empty string (`''`)

I initially raised this issue in the rdkit repo but Greg indicated that this is an issue with the packaging for pip.

**Configuration**
 - RDKit version: 2023.09.3
 - OS: Ubuntu 22.04.2 LTS (under WSL2)
 - Python version: 3.10.12
 - Are you using conda? No
 - If you are not using conda: how did you install the RDKit? `pip install rdkit`

**Comment by kuelumbus** [comment]
Thanks for reporting this.👍 This is an issue with the Conan cmake generator not setting the `Boost_LIB_VERSION` variable. Linking Boost and running RDKit should not be affected by this. FYI, the boost version is currently at 1.78.0.
 
Should be fixed in the next release.

**Comment by radusuciu** [comment]
Thanks for the quick fix! I'll check it out upon release.
