### ISSUE TITLE
Missing wheels on PyPI due to size limit for RDKit versions larger than 2023.9.6

### ISSUE THREAD

**Issue by kuelumbus** [kuelumbus/rdkit-pypi#99]
Waiting for https://github.com/pypi/support/issues/3962 to be resolved.

**Comment by fxcoudert** [comment]
Resolved: https://x.com/cmaureir/status/1805179673325838659

**Comment by kuelumbus** [comment]
Finally this has been resolve. I will push the new PyPI versions in the next couple of week.
